global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: db-benchmark-app-mysql
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["app-mysql:8090"]
        labels:
          database: mysql

  - job_name: db-benchmark-app-postgres
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["app-postgres:8090"]
        labels:
          database: postgres

  - job_name: mysqld-exporter
    static_configs:
      - targets: ["mysqld-exporter:9104"]

  - job_name: postgres-exporter
    static_configs:
      - targets: ["postgres-exporter:9187"]

  - job_name: mongodb-exporter
    static_configs:
      - targets: ["mongodb-exporter:9216"]

  - job_name: pushgateway
    honor_labels: true
    static_configs:
      - targets: ["pushgateway:9091"]

  - job_name: cadvisor
    static_configs:
      - targets: ["cadvisor:8080"]

  - job_name: node-exporter
    static_configs:
      - targets: ["node-exporter:9100"]
